# 使用较新的 Compose 文件版本
#version: '3.8'

# 定义我们要运行的服务
services:
  # 我们为 PostgreSQL 服务起个名字叫 postgres-db
  postgres-db:
    # 使用官方的 PostgreSQL 镜像，版本16。alpine版本体积更小，启动更快。
    image: postgres:16-alpine
    # 给运行的容器起一个固定的名字，方便我们管理
    container_name: studyapp-postgres
    # 配置环境变量，用于初始化数据库
    environment:
      POSTGRES_USER: study_user # 定义数据库用户名
      POSTGRES_PASSWORD: study_password # 定义数据库密码
      POSTGRES_DB: study_app_db # 定义要创建的数据库名称
    # 将容器的5432端口映射到我们电脑的5432端口
    # 这样我们的Spring Boot应用就可以通过 localhost:5432 访问到容器里的数据库
    ports:
      - "5432:5432"
    # 数据持久化配置。这可以确保即使容器被删除，我们的数据库数据也不会丢失。
    volumes:
      - postgres-data:/var/lib/postgresql/data

# 定义一个命名的卷，用于持久化存储PostgreSQL的数据
volumes:
  postgres-data: